### ISSUE TITLE
Is it necessary to download whole ScanNet dataset?

### ISSUE THREAD

**Issue by lifuguan** [liuff19/Semantic-Ray#2]
ScanNet is so big, is it necessary to download the whole dataset? If so, it'll be appreciated if you can provide a download link with the preprocessed dataset.

**Comment by LinShan-Bin** [comment]
We are only permitted to share the dataset with our associates and colleagues who have agreed to abide by ScanNet's terms and conditions. Therefore, it would be inappropriate for us to provide a public link. Instead, we recommend that you customize the official download script to specifically download the scans you require.

**Comment by lifuguan** [comment]
Thanks for reply. Meanwhile, the official data preprocess script (https://github.com/ScanNet/ScanNet/tree/master/SensReader/python) can only organize the data in the following format:
```bash
│   │   ├── scene0000_00
│   │   │   ├── color
│   │   │   │   ├── 0.jpg
│   │   │   │   ├── ...
│   │   │   ├── depth
│   │   │   │   ├── 0.png
│   │   │   │   ├── ...
│   │   │   ├── pose
│   │   │   │   ├── 0.txt
│   │   │   │   ├── ...
│   │   │   ├── intrinsic
```
, where the `label-filt` is missing. Would you provide the preprocess script for ScanNet? Best regard.

**Comment by LinShan-Bin** [comment]
`label-filt` is extracted from `<scan_id>_2d-label-filt.zip` in each scan folder. Here is a simple script to do that:
```shell
for folder in */; do
  if [[ -d "$folder" ]]; then
    scanId="${folder%/}"
    zipFile="${scanId}_2d-label-filt.zip"
    labelFolder="${scanId}/label-filt"
    if [[ -f "$folder$zipFile" ]]; then
      mkdir -p "$labelFolder"
      unzip -q "$folder$zipFile" -d "$labelFolder"
    fi
  fi
done
```
